title: vemek.co
author: Mark King
email: mark at vemek dot co
description: >-
  A blog about technical things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vemek.co" # the base hostname & protocol for your site, e.g. http://example.com
github_username: vemek

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
